#pragma once

enum class MOS6510MicroOperation
{
    NoOperation,

    ReadImmediateToAccumulator,
    ReadImmediateToXRegister,
    ReadImmediateToYRegister,
    ReadImmediateAndAccumulator,
    ReadImmediateOrAccumulator,
    ReadImmediateExclusiveOrAccumulator,
    ReadImmediateAddToAccumulator,
    ReadImmediateSubtractFromAccumulator,
    ReadImmediateCompareAccumulator,
    ReadImmediateCompareXRegister,
    ReadImmediateCompareYRegister,

    ReadZeroPageAddress,
    ReadZeroPageToAccumulator,
    ReadZeroPageToXRegister,
    ReadZeroPageToYRegister,
    ReadZeroPageAndAccumulator,
    ReadZeroPageOrAccumulator,
    ReadZeroPageExclusiveOrAccumulator,
    ReadZeroPageAddToAccumulator,
    ReadZeroPageSubtractFromAccumulator,
    ReadZeroPageCompareAccumulator,
    ReadZeroPageCompareXRegister,
    ReadZeroPageCompareYRegister,

    ReadZeroPageIndexedAddress,
    ReadZeroPageIndexedToAccumulator,
    ReadZeroPageIndexedToXRegister,
    ReadZeroPageIndexedToYRegister,
    ReadZeroPageIndexedAndAccumulator,
    ReadZeroPageIndexedOrAccumulator,
    ReadZeroPageIndexedExclusiveOrAccumulator,
    ReadZeroPageIndexedAddToAccumulator,
    ReadZeroPageIndexedSubtractFromAccumulator,
    ReadZeroPageIndexedCompareAccumulator,

    ReadAbsoluteAddressLow,
    ReadAbsoluteAddressHigh,
    ReadAbsoluteXAddress,
    ReadAbsoluteYAddress,
    ReadAbsoluteIndexedDummy,
    ReadAbsoluteToAccumulator,
    ReadAbsoluteToXRegister,
    ReadAbsoluteToYRegister,
    ReadAbsoluteAndAccumulator,
    ReadAbsoluteOrAccumulator,
    ReadAbsoluteExclusiveOrAccumulator,
    ReadAbsoluteAddToAccumulator,
    ReadAbsoluteSubtractFromAccumulator,
    ReadAbsoluteCompareAccumulator,
    ReadAbsoluteCompareXRegister,
    ReadAbsoluteCompareYRegister,

    ReadAbsoluteIndexedToAccumulator,
    ReadAbsoluteIndexedToXRegister,
    ReadAbsoluteIndexedToYRegister,
    ReadAbsoluteIndexedAndAccumulator,
    ReadAbsoluteIndexedOrAccumulator,
    ReadAbsoluteIndexedExclusiveOrAccumulator,
    ReadAbsoluteIndexedAddToAccumulator,
    ReadAbsoluteIndexedSubtractFromAccumulator,
    ReadAbsoluteIndexedCompareAccumulator,

    ReadIndirectAddressLow,
    ReadIndirectAddressHigh,
    ReadIndirectAddressHighIndexed,
    ReadIndirectToAccumulator,
    ReadIndirectAddToAccumulator,
    ReadIndirectSubtractFromAccumulator,
    ReadIndirectCompareAccumulator,

    ReadIndirectIndexedToAccumulator,
    ReadIndirectIndexedAddToAccumulator,
    ReadIndirectIndexedSubtractFromAccumulator,
    ReadIndirectIndexedCompareAccumulator,

    WriteAccumulator,
    WriteXRegister,
    WriteYRegister,

    IncrementXRegister,
    IncrementYRegister,
    DecrementXRegister,
    DecrementYRegister,

    ReadMemoryToData,
    WriteDataToMemory,
    IncrementDataAndWriteToMemory,
    DecrementDataAndWriteToMemory,

    TransferAccumulatorToXRegister,
    TransferAccumulatorToYRegister,
    TransferXRegisterToAccumulator,
    TransferYRegisterToAccumulator,
    TransferStackPointerToXRegister,
    TransferXRegisterToStackPointer,

    WriteAccumulatorToStack,
    ReadStackToAccumulator,
    WriteStatusToStack,
    ReadStackToStatus,
    ReadStackDummy,

    SetDecimalFlag,
    ClearDecimalFlag


};
